CREATE DATABASE IF NOT EXISTS repgen;

USE repgen;

CREATE TABLE IF NOT EXISTS template (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
);
  
DROP TABLE template;

CREATE TABLE IF NOT EXISTS Employee (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  privileges VARCHAR(128)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Client (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Building (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  client_id BIGINT UNSIGNED NOT NULL,
  address VARCHAR(256) NOT NULL,
  status VARCHAR(64) NOT NULL,
  CONSTRAINT `fk_client_building` FOREIGN KEY (client_id) REFERENCES Client(id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Visit (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  date DATE NOT NULL,
  car VARCHAR(32) 
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Activity (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  visit_id BIGINT UNSIGNED NOT NULL,
  description VARCHAR(256) NOT NULL,
  CONSTRAINT `fk_visit_activity` FOREIGN KEY (visit_id) REFERENCES Visit(id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Observation (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  visit_id BIGINT UNSIGNED NOT NULL,
  description VARCHAR(256) NOT NULL,
  CONSTRAINT `fk_visit_observation` FOREIGN KEY (visit_id) REFERENCES Visit(id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Pendency (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  visit_id BIGINT UNSIGNED NOT NULL,
  description VARCHAR(256) NOT NULL,
  CONSTRAINT `fk_visit_pendency` FOREIGN KEY (visit_id) REFERENCES Visit(id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Makes_visit (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  visit_id BIGINT UNSIGNED NOT NULL,
  employee_id BIGINT UNSIGNED NOT NULL,
  CONSTRAINT `fk_employee` FOREIGN KEY (employee_id) REFERENCES Employee(id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Recieves_visit(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  visit_id BIGINT UNSIGNED NOT NULL,
  building_id BIGINT UNSIGNED NOT NULL,
  CONSTRAINT `fk_visit_recieves` FOREIGN KEY (visit_id) REFERENCES Visit(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_building_recieves` FOREIGN KEY (building_id) REFERENCES Building(id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB;