CREATE TABLE IF NOT EXISTS User (
    id      SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name    VARCHAR(128) NOT NULL,
    privileges VARCHAR(30) NOT NULL,
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Client (
    id      MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name    VARCHAR(128) NOT NULL,
    address VARCHAR(250) NOT NULL,
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Observations (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    observation VARCHAR(250),
);

CREATE TABLE IF NOT EXISTS Pendencies (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    pendency VARCHAR(250),
);

CREATE TABLE IF NOT EXISTS Activities (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    activity VARCHAR(250),
);

DROP TABLE IF EXISTS Report;

CREATE TABLE IF NOT EXISTS Report (
    id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    activities_id   BIGINT UNSIGNED NOT NULL,
    pendencies_id   BIGINT UNSIGNED NOT NULL,
    observations_id BIGINT UNSIGNED NOT NULL,
    CONSTRAINT `fk_activities` FOREIGN KEY (activities_id) REFERENCES Activities(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT `fk_pendencies` FOREIGN KEY (pendencies_id) REFERENCES Pendencies(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT `fk_observations` FOREIGN KEY (observations_id) REFERENCES Observations(id) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE = InnoDB;

DROP TABLE IF EXISTS Visit;

CREATE TABLE IF NOT EXISTS Visit (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id     SMALLINT UNSIGNED NOT NULL,
    client_id   MEDIUMINT UNSIGNED NOT NULL,
    report_id   BIGINT UNSIGNED NOT NULL,
    date        DATE NOT NULL,
    CONSTRAINT `fk_user` FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `fk_client` FOREIGN KEY (client_id) REFERENCES Client(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `fk_report` FOREIGN KEY (report_id) REFERENCES Report(id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB;

