CREATE TABLE IF NOT EXISTS User (
    id      SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name    VARCHAR(128) NOT NULL,
    privileges VARCHAR(30) NOT NULL,
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Client (
    id      MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name    VARCHAR(128) NOT NULL,
    address VARCHAR(250) NOT NULL,
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Report (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    client_id   MEDIUMINT UNSIGNED NOT NULL,
    date        DATE NOT NULL,
    CONSTRAINT `fk_client` FOREIGN KEY (client_id) REFERENCES Client(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Visits (
    id            MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id       BIGINT UNSIGNED NOT NULL,
    report_id     BIGINT UNSIGNED NOT NULL,
    CONSTRAINT `fk_user` FOREIGN KEY (user_id) REFERENCES User(id) ON DELET RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `fk_report` FOREING KEY (report_id) REFERENCES Report(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Observations (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    observation VARCHAR(250),
);

CREATE TABLE IF NOT EXISTS Pendencies (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    pendency VARCHAR(250),
);

CREATE TABLE IF NOT EXISTS Activities (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    activity VARCHAR(250),
);

DROP TABLE IF EXISTS Report;

DROP TABLE IF EXISTS Visit;
